service: LambdaDemo6 
provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: sentinel-serverless-1
  stage: dev
  region: us-west-2

  # Specifies the version of the HTTP API payload sent to the Lambda.
  # If the REST API is required, remove this and specify 'http' 
  # instead of 'httpApi' for the events below.
  httpApi:
    payload: '2.0'

functions:
  hello:
    handler: 'LambdaDemo6::MySpace.LambdaEntryPoint::FunctionHandlerAsync'
    package:
      artifact: bin/release/netcoreapp3.1/hello.zip
    events:
      # This will construct an HTTP API endpoint to integrate with the Lambda.
      - httpApi: '*'