service: lambdademo3-david
frameworkVersion: '2'
provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: sentinel-serverless-1
  stage: dev
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "BucketDemo" } ] ]  }

package:
  individually: true

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip
resources:
 Resources:
   BucketDemo:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: sentinel-serverless-demo1
