Description: Creates an S3 bucket and attaches a policy based on a conditional parameter
Parameters:
  IncludeBucketPolicy:
    Description: Whether to include the policy for this bucket.
    Type: String
    # We're going to match based on this string value of "yes" versus "no".
    # Note that in YAML, yes/no without the quotes may be interpreted as boolean
    # and currently would show in the AWS dashboard as true/false.
    # 
    # Using quotes here eliminates any ambiguity.
    AllowedValues: ['yes','no']
    Default: 'no'
# This section defines the condition we'll use on resources in the template.
Conditions:
  ShouldCreatePolicy: !Equals ['yes', !Ref IncludeBucketPolicy]
Resources:
  BucketExample:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: super-simple-cf-syrup
  BucketPolicyExample:
    Type: AWS::S3::BucketPolicy
    # Here is our reference to the conditional input crafted above.
    Condition: ShouldCreatePolicy
    Properties:
      Bucket: !Ref BucketExample
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref BucketExample
                - /*
            Principal: '*'
            Condition:
              StringLike:
                'aws:Referer':
                  - 'http://www.example.com/*'
                  - 'http://example.net/*'

